const STORAGE_USER='siga30_portal_user_v2';
const STORAGE_DATA='siga30_portal_data_v2';
const STORAGE_API='siga30_portal_api_v1';

const state={
  user:null,
  permissions:{separacoes:true,carregamentos:true,atividades:true,desempenho:true,conferencias:false,admin:false},
  page:'home',
  lastSync:null,
  syncing:false
};

const sampleSeps=[
 {lote:'LT-1025',pedido:'PED-4587',destino:'Ponte Nova',peso:'860 kg',volumes:'42',inicio:'08:15',fim:'09:02',status:'Finalizada',resultado:'OK',usuario_id:'joao.silva'},
 {lote:'LT-1038',pedido:'PED-4621',destino:'Viçosa',peso:'620 kg',volumes:'31',inicio:'10:20',fim:'11:10',status:'Em andamento',resultado:'',usuario_id:'joao.silva'},
 {lote:'LT-1029',pedido:'PED-4601',destino:'Ubá',peso:'740 kg',volumes:'38',inicio:'11:45',fim:'12:30',status:'Finalizada',resultado:'OK',usuario_id:'joao.silva'},
 {lote:'LT-1030',pedido:'PED-4590',destino:'Rio Casca',peso:'510 kg',volumes:'25',inicio:'13:12',fim:'14:05',status:'Finalizada',resultado:'OK',usuario_id:'joao.silva'},
 {lote:'LT-1018',pedido:'PED-4560',destino:'Mariana',peso:'380 kg',volumes:'18',inicio:'15:20',fim:'16:10',status:'Pendente',resultado:'',usuario_id:'joao.silva'}
];
const sampleCars=[
 {romaneio:'ROM-783',destino:'Ponte Nova',motorista:'João Silva',placa:'OFA-4452',peso:'12.500 kg',volumes:'48',inicio:'10:20',fim:'12:05',resultado:'OK',status:'Finalizado',usuario_id:'joao.silva'},
 {romaneio:'ROM-782',destino:'Ubá',motorista:'Carlos Lima',placa:'OQP-9621',peso:'8.600 kg',volumes:'36',inicio:'11:20',fim:'12:06',resultado:'OK',status:'Finalizado',usuario_id:'joao.silva'},
 {romaneio:'ROM-781',destino:'Rio Casca',motorista:'Pedro Alves',placa:'HKG-7810',peso:'7.400 kg',volumes:'28',inicio:'09:10',fim:'11:00',resultado:'NÃO OK',status:'Finalizado',usuario_id:'joao.silva'},
 {romaneio:'ROM-780',destino:'Mariana',motorista:'Rafael Souza',placa:'KBS-2055',peso:'5.400 kg',volumes:'20',inicio:'08:10',fim:'09:50',resultado:'OK',status:'Finalizado',usuario_id:'joao.silva'}
];
const sampleActs=[
 {hora:'08:15',tipo:'Separação',descricao_original:'Início da separação • LT-1025 • Ponte Nova',status:'Em andamento',usuario_id:'joao.silva'},
 {hora:'09:02',tipo:'Separação',descricao_original:'Separação finalizada • LT-1025',status:'Finalizada',usuario_id:'joao.silva'},
 {hora:'09:10',tipo:'Conferência',descricao_original:'Conferência • PED-4587',status:'OK',usuario_id:'joao.silva'},
 {hora:'10:20',tipo:'Carregamento',descricao_original:'Início do carregamento • ROM-783 • Viçosa',status:'Em andamento',usuario_id:'joao.silva'},
 {hora:'11:05',tipo:'Carregamento',descricao_original:'Carregamento finalizado • ROM-783',status:'OK',usuario_id:'joao.silva'},
 {hora:'12:15',tipo:'Conferência',descricao_original:'Conferência • PED-4612 • 3 volumes divergentes',status:'NÃO OK',usuario_id:'joao.silva'},
 {hora:'13:30',tipo:'Carregamento',descricao_original:'Carregamento finalizado • ROM-785 • 2 volumes divergentes',status:'NÃO OK',usuario_id:'joao.silva'}
];
const sampleConfs=[
 {operacao:'Separação',referencia:'PED-4587',hora:'09:10',resultado:'OK',ocorrencia:'—',quantidade_divergente:'—',observacao:'—',usuario_id:'joao.silva'},
 {operacao:'Separação',referencia:'LT-1025',hora:'10:45',resultado:'OK',ocorrencia:'—',quantidade_divergente:'—',observacao:'—',usuario_id:'joao.silva'},
 {operacao:'Carregamento',referencia:'ROM-783',hora:'12:15',resultado:'OK',ocorrencia:'—',quantidade_divergente:'—',observacao:'—',usuario_id:'joao.silva'},
 {operacao:'Conferência',referencia:'PED-4612',hora:'12:15',resultado:'NÃO OK',ocorrencia:'3 volumes',quantidade_divergente:'3',observacao:'Volumes faltantes',usuario_id:'joao.silva'},
 {operacao:'Carregamento',referencia:'ROM-785',hora:'13:30',resultado:'NÃO OK',ocorrencia:'2 volumes',quantidade_divergente:'2',observacao:'Volumes a menos',usuario_id:'joao.silva'}
];
const users=[['JS','João Silva','Operador','Separação • Carregamento • Atividades'],['CS','Carlos Souza','Conferente','Conferência • Atividades'],['PA','Pedro Alves','Operador + Conferente','Todas as funções'],['RM','Rafael Mendes','Operador','Separação • Atividades']];

let portalData=loadData();
function loadData(){
 try{const x=JSON.parse(localStorage.getItem(STORAGE_DATA)||'null');return {separacoes:Array.isArray(x?.separacoes)?x.separacoes:sampleSeps,carregamentos:Array.isArray(x?.carregamentos)?x.carregamentos:sampleCars,atividades:Array.isArray(x?.atividades)?x.atividades:sampleActs,conferencias:Array.isArray(x?.conferencias)?x.conferencias:sampleConfs};}
 catch{return {separacoes:sampleSeps,carregamentos:sampleCars,atividades:sampleActs,conferencias:sampleConfs};}
}
function saveData(){localStorage.setItem(STORAGE_DATA,JSON.stringify(portalData));}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function norm(v){return String(v??'').trim().toLowerCase();}
function sameUser(o){
 const u=state.user||{}; const ids=[o.usuario_id,o.user_id,o.operador_id,o.conferente_id,o.usuario,o.operador,o.conferente].filter(Boolean).map(norm);
 const names=[u.id,u.usuario,u.username,u.login,u.name,u.nome].filter(Boolean).map(norm);
 if(!ids.length)return true;
 return ids.some(id=>names.includes(id)||names.some(n=>id===n));
}
function resultClass(v){const x=norm(v);return x==='ok'||x==='finalizada'||x==='finalizado'?'ok':x.includes('não ok')||x.includes('nao ok')?'bad':'pending';}
function badge(t,c){return `<span class="badge ${c||resultClass(t)}">${esc(t)}</span>`;}
function bar(label,value,max,cls=''){const pct=max?Math.min(100,Math.round(value/max*100)):0;return `<div class="bar-row"><label>${esc(label)}</label><div class="bar"><div class="fill ${cls}" style="width:${pct}%"></div></div><strong>${value}</strong></div>`;}
function tablePage(title,sub,heads,rows){return `<div class="page-title"><h1>${esc(title)}</h1><p>${esc(sub)}</p></div><div class="panel"><div class="filters"><input placeholder="Pesquisar..." oninput="filterRows(this.value)"><select id="periodFilter"><option>Hoje</option><option>Últimos 7 dias</option><option>Este mês</option></select><select id="statusFilter"><option>Todos os status</option><option>Finalizada</option><option>Em andamento</option><option>OK</option><option>NÃO OK</option></select><button class="btn" onclick="applyFilters()">Filtrar</button></div><div class="table-wrap"><table class="table"><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody id="dataRows">${rows||'<tr><td colspan="20" class="empty">Nenhum registro encontrado.</td></tr>'}</tbody></table></div></div>`;}
function userSeps(){return portalData.separacoes.filter(sameUser);}
function userCars(){return portalData.carregamentos.filter(sameUser);}
function userActs(){return portalData.atividades.filter(sameUser);}
function userConfs(){return portalData.conferencias.filter(sameUser);}
function totals(){const s=userSeps(),c=userCars(),f=userConfs(),a=userActs();return {s:s.length,c:c.length,f:f.length,a:a.length,fok:f.filter(x=>norm(x.resultado)==='ok').length,fbad:f.filter(x=>norm(x.resultado).includes('não ok')||norm(x.resultado).includes('nao ok')).length,cok:c.filter(x=>norm(x.resultado)==='ok').length,cbad:c.filter(x=>norm(x.resultado).includes('não ok')||norm(x.resultado).includes('nao ok')).length};}
function navItems(){return [['home','⌂','Início',true],['separacoes','▣','Minhas Separações',state.permissions.separacoes],['carregamentos','▰','Meus Carregamentos',state.permissions.carregamentos],['conferencias','✓','Minhas Conferências',state.permissions.conferencias],['atividades','◷','Minhas Atividades',state.permissions.atividades],['desempenho','▥','Meu Desempenho',state.permissions.desempenho],['perfil','●','Perfil / Acesso',true],['admin','⚙','Gestão de Usuários',state.permissions.admin],['logout','↪','Sair',true]];}
function renderNav(){const el=document.querySelector('#nav');if(!el)return;el.innerHTML=navItems().filter(x=>x[3]).map(x=>`<button class="nav-item ${state.page===x[0]?'active':''}" data-page="${x[0]}"><span class="nav-icon">${x[1]}</span>${esc(x[2])}</button>`).join('');el.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{const p=b.dataset.page;if(p==='logout'){logout();return;}state.page=p;render();});}
function updateUserUI(){if(!state.user)return;const n=state.user.name||state.user.nome||'Usuário';const initials=(state.user.avatar||n.split(/\s+/).map(x=>x[0]).join('').slice(0,2)).toUpperCase();['sideInitials','headerInitials'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=initials;});const sn=document.getElementById('sideName');if(sn)sn.textContent=n;const sr=document.getElementById('sideRole');if(sr)sr.textContent=state.user.role||'Operador';const hw=document.getElementById('headerWho');if(hw)hw.textContent=`${state.user.cd||'CDD'} · ${n}`;}
function render(){if(!state.user)return;document.querySelector('#login')?.classList.add('hide');document.querySelector('#app')?.classList.remove('hide');updateUserUI();renderNav();const pages={home,separacoes:separacoesPage,carregamentos:carregamentosPage,conferencias:conferenciasPage,atividades:atividadesPage,desempenho:desempenhoPage,perfil:perfilPage,admin:adminPage};const main=document.querySelector('#main');if(main)main.innerHTML=(pages[state.page]||home)();closeMenu();}
function home(){const t=totals();const acts=userActs();return `<div class="hero"><div><div class="eyebrow">Painel do usuário</div><h1>Olá, ${esc((state.user.name||'Usuário').split(' ')[0])}!</h1><p>Aqui está o resumo das suas atividades de hoje.</p></div><button class="btn secondary" onclick="refreshData(true)">↻ Atualizar agora</button></div><div class="cards"><div class="stat blue"><div class="stat-top"><span>SEPARAÇÕES</span><span class="stat-icon">▣</span></div><strong>${t.s}</strong><small>Hoje</small></div><div class="stat green"><div class="stat-top"><span>CARREGAMENTOS</span><span class="stat-icon">▰</span></div><strong>${t.c}</strong><small>Hoje</small></div><div class="stat purple"><div class="stat-top"><span>CONFERÊNCIAS</span><span class="stat-icon">✓</span></div><strong>${t.f}</strong><small>Hoje</small></div><div class="stat dark"><div class="stat-top"><span>ATIVIDADES</span><span class="stat-icon">☷</span></div><strong>${t.a}</strong><small>Hoje</small></div></div><div class="grid2"><div class="panel"><div class="panel-title"><div><h3>📋 Atividades feitas hoje</h3><div class="sub">Registro individual do usuário</div></div><button class="btn secondary" onclick="state.page='atividades';render()">Ver todas →</button></div><div class="timeline">${acts.length?acts.map(e=>`<div class="event"><span class="dot"></span><div><b>${esc(e.hora||e.inicio||'')} • ${esc(e.tipo||'Atividade')}</b><small>${esc(e.descricao_original||e.descricao||e.atividade||e.texto||'')}</small></div>${badge(e.status||'PENDENTE',resultClass(e.status))}</div>`).join(''):'<div class="empty">Nenhuma atividade registrada.</div>'}</div></div><div><div class="panel"><h3>📊 Atividades de hoje</h3><div class="sub">Gráfico horizontal</div>${bar('Separações',t.s,Math.max(t.s,t.c,t.f,t.a,1),'')}${bar('Carregamentos',t.c,Math.max(t.s,t.c,t.f,t.a,1),'green')}${bar('Conferências',t.f,Math.max(t.s,t.c,t.f,t.a,1),'purple')}${bar('Atividades',t.a,Math.max(t.s,t.c,t.f,t.a,1),'dark')}</div><div class="panel"><h3>📈 Resultados das operações</h3><div class="sub">OK e NÃO OK</div>${bar('Conferências OK',t.fok,Math.max(t.f,1),'green')}${bar('Conferências NÃO OK',t.fbad,Math.max(t.f,1),'red')}${bar('Carregamentos OK',t.cok,Math.max(t.c,1),'green')}${bar('Carregamentos NÃO OK',t.cbad,Math.max(t.c,1),'red')}</div></div></div><div class="sub" style="margin-top:10px">Última atualização: ${esc(state.lastSync?new Date(state.lastSync).toLocaleTimeString('pt-BR'):'agora')}</div>`;}
function separacoesPage(){const d=userSeps();return tablePage('Minhas Separações','Apenas separações vinculadas ao seu usuário.',['Lote','Pedido','Destino','Peso','Volumes','Início','Fim','Status',''],d.map(r=>`<tr><td>${esc(r.lote||r.numero_lote)}</td><td>${esc(r.pedido||r.numero_pedido)}</td><td>${esc(r.destino||r.rota)}</td><td>${esc(r.peso||r.peso_total_kg)}</td><td>${esc(r.volumes||r.volume_total)}</td><td>${esc(r.inicio)}</td><td>${esc(r.fim)}</td><td>${badge(r.status||'PENDENTE',resultClass(r.status||r.resultado))}</td><td><button class="btn secondary" onclick="details('${esc(r.lote||'')}')">Ver</button></td></tr>`).join(''));}
function carregamentosPage(){const d=userCars();return tablePage('Meus Carregamentos','Apenas carregamentos vinculados ao seu usuário.',['Romaneio','Rota/Destino','Motorista','Placa','Peso','Volumes','Início','Fim','Resultado'],d.map(r=>`<tr><td>${esc(r.romaneio||r.numero_romaneio)}</td><td>${esc(r.destino||r.rota)}</td><td>${esc(r.motorista)}</td><td>${esc(r.placa||r.veiculo)}</td><td>${esc(r.peso||r.peso_total_kg)}</td><td>${esc(r.volumes||r.volume_total)}</td><td>${esc(r.inicio)}</td><td>${esc(r.fim)}</td><td>${badge(r.resultado||r.status||'PENDENTE',resultClass(r.resultado||r.status))}</td></tr>`).join(''));}
function conferenciasPage(){const d=userConfs();return tablePage('Minhas Conferências','Somente usuários com permissão de conferência.',['Operação','Lote/Pedido','Data/Hora','Resultado','Divergência','Qtd. divergente','Observação'],d.map(r=>`<tr><td>${esc(r.operacao||r.tipo_operacao)}</td><td>${esc(r.referencia||r.lote||r.pedido)}</td><td>${esc(r.hora||r.fim||r.inicio)}</td><td>${badge(r.resultado||'PENDENTE',resultClass(r.resultado))}</td><td>${esc(r.ocorrencia||'—')}</td><td>${esc(r.quantidade_divergente||r.qtd||'—')}</td><td>${esc(r.observacao||'—')}</td></tr>`).join(''));}
function atividadesPage(){const d=userActs();return tablePage('Minhas Atividades','Preserva a descrição original registrada no SIGA, mesmo quando o texto varia.',['Hora','Tipo','Descrição original','Status','Detalhes'],d.map(e=>`<tr><td>${esc(e.hora||e.inicio||'')}</td><td>${esc(e.tipo||'Atividade')}</td><td>${esc(e.descricao_original||e.descricao||e.atividade||e.texto||e.detalhes||'')}</td><td>${badge(e.status||'PENDENTE',resultClass(e.status))}</td><td><button class="btn secondary" onclick="showToast('Detalhes da atividade')">Ver</button></td></tr>`).join(''));}
function desempenhoPage(){const t=totals();const max=Math.max(t.s,t.c,t.f,t.a,1);return `<div class="page-title"><h1>Meu Desempenho</h1><p>Resumo calculado a partir das operações vinculadas ao usuário.</p></div><div class="cards"><div class="stat blue"><div class="stat-top">SEPARAÇÕES</div><strong>${t.s}</strong><small>Registros</small></div><div class="stat green"><div class="stat-top">CARREGAMENTOS</div><strong>${t.c}</strong><small>Registros</small></div><div class="stat purple"><div class="stat-top">CONFERÊNCIAS</div><strong>${t.f}</strong><small>Registros</small></div><div class="stat dark"><div class="stat-top">ATIVIDADES</div><strong>${t.a}</strong><small>Registros</small></div></div><div class="grid2"><div class="panel"><h3>Desempenho</h3><div class="sub">Indicadores em barras horizontais</div>${bar('Separações',t.s,max,'')}${bar('Carregamentos',t.c,max,'green')}${bar('Conferências',t.f,max,'purple')}${bar('Atividades',t.a,max,'dark')}</div><div class="panel"><h3>Resultados</h3><div class="sub">Conferências e carregamentos</div>${bar('Conferências OK',t.fok,Math.max(t.f,1),'green')}${bar('Conferências NÃO OK',t.fbad,Math.max(t.f,1),'red')}${bar('Carregamentos OK',t.cok,Math.max(t.c,1),'green')}${bar('Carregamentos NÃO OK',t.cbad,Math.max(t.c,1),'red')}</div></div>`;}
function perfilPage(){return `<div class="page-title"><h1>Perfil / Acesso</h1><p>Seu perfil e as permissões liberadas pelo administrador.</p></div><div class="profile"><div class="panel profile-card"><div class="avatar">${esc(state.user.avatar||'US')}</div><h3>${esc(state.user.name)}</h3><p class="sub">${esc(state.user.role||'Operador')}</p><div class="info" style="margin-top:15px;text-align:left"><small>Unidade</small><b>${esc(state.user.cd||'CDD')}</b></div></div><div class="panel"><h3>Permissões</h3>${permission('separacoes','Visualizar minhas separações')}${permission('carregamentos','Visualizar meus carregamentos')}${permission('atividades','Visualizar minhas atividades')}${permission('desempenho','Visualizar meu desempenho')}${permission('conferencias','Visualizar minhas conferências')}<button class="btn" style="margin-top:12px" onclick="showToast('Permissões administradas pelo perfil Autor')">Solicitar alteração</button></div></div>`;}
function permission(k,label){return `<div class="permission"><input type="checkbox" ${state.permissions[k]?'checked':''} disabled> ${esc(label)}</div>`;}
function adminPage(){return `<div class="page-title"><h1>Gestão de Usuários e Permissões</h1><p>Perfil Autor / Administrador • crie usuários, senhas e libere funções individualmente.</p></div><div class="admin-grid"><div class="panel"><div class="panel-title"><div><h3>👤 Usuários cadastrados</h3><div class="sub">Acesso controlado por usuário</div></div><button class="btn" onclick="showToast('Formulário de novo usuário')">+ Criar usuário</button></div><div class="user-list" style="margin-top:12px">${users.map(u=>`<div class="user-row"><div class="avatar">${u[0]}</div><div><b>${esc(u[1])}</b><small>${esc(u[2])} • ${esc(u[3])}</small></div><button class="btn secondary" onclick="showToast('Editando ${esc(u[1])}')">Editar</button></div>`).join('')}</div></div><div class="panel"><h3>🔐 Novo acesso</h3><div class="filters" style="margin-top:12px"><input placeholder="Nome completo"><input placeholder="Usuário"><input placeholder="Criar senha"><select><option>Operador</option><option>Conferente</option><option>Operador + Conferente</option><option>Administrador</option></select></div><h3 style="margin-top:8px">Liberar funções</h3><div class="checkgrid"><label class="check"><input type="checkbox" checked> Minhas Separações</label><label class="check"><input type="checkbox"> Meus Carregamentos</label><label class="check"><input type="checkbox" checked> Minhas Atividades</label><label class="check"><input type="checkbox"> Meu Desempenho</label><label class="check"><input type="checkbox"> Minhas Conferências</label></div><button class="btn" style="margin-top:13px" onclick="showToast('Usuário criado com permissões selecionadas')">Criar acesso</button></div></div>`;}
function details(lote){const r=userSeps().find(x=>(x.lote||x.numero_lote)===lote)||userSeps()[0];if(!r){state.page='separacoes';render();return;}document.querySelector('#main').innerHTML=`<div class="page-title"><button class="btn secondary" onclick="render()">← Voltar</button><h1 style="margin-top:8px">Detalhes da separação</h1><p>Operação ${esc(lote)}</p></div><div class="panel"><div class="hero"><div><h1 style="font-size:16px">Lote ${esc(r.lote||'')}</h1><p>Pedido ${esc(r.pedido||'')} • Destino ${esc(r.destino||'')}</p></div>${badge(r.status||'PENDENTE',resultClass(r.status||r.resultado))}</div><div class="detail-grid"><div class="info"><small>Peso</small><b>${esc(r.peso||'')}</b></div><div class="info"><small>Volumes</small><b>${esc(r.volumes||'')}</b></div><div class="info"><small>Início</small><b>${esc(r.inicio||'')}</b></div><div class="info"><small>Fim</small><b>${esc(r.fim||'')}</b></div></div></div>`;}
function filterRows(v){const q=norm(v);document.querySelectorAll('#dataRows tr').forEach(r=>r.style.display=norm(r.innerText).includes(q)?'':'none');}
function applyFilters(){const q=document.querySelector('.filters input')?.value||'';filterRows(q);showToast('Filtro aplicado');}
function showToast(m){const t=document.querySelector('#toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}}
function closeMenu(){document.querySelector('#sidebar')?.classList.remove('open');document.querySelector('#overlay')?.classList.remove('show');document.querySelector('aside')?.classList.remove('open');}
function login(){const u=(document.querySelector('#u')?.value||'').trim();const p=document.querySelector('#pw')?.value||'';const msg=document.querySelector('#loginmsg');if(!u||!p){if(msg)msg.textContent='Informe usuário e senha.';return;}state.user={id:u.toLowerCase(),usuario:u,username:u,name:u==='01022005'?'Marco':u,role:u==='01022005'?'Autor / Administrador':'Operador',cd:document.querySelector('#fil')?.value||'CDD',avatar:(u==='01022005'?'MA':u.slice(0,2).toUpperCase())};state.permissions={separacoes:true,carregamentos:true,atividades:true,desempenho:true,conferencias:u==='01022005',admin:u==='01022005'};localStorage.setItem(STORAGE_USER,JSON.stringify(state.user));localStorage.setItem('siga30_portal_permissions_v2',JSON.stringify(state.permissions));state.page='home';render();refreshData(true);}
function logout(){localStorage.removeItem(STORAGE_USER);localStorage.removeItem('siga30_portal_permissions_v2');state.user=null;document.querySelector('#app')?.classList.add('hide');document.querySelector('#login')?.classList.remove('hide');}
function restoreSession(){try{const u=JSON.parse(localStorage.getItem(STORAGE_USER)||'null');if(!u)return false;state.user=u;const p=JSON.parse(localStorage.getItem('siga30_portal_permissions_v2')||'null');if(p)state.permissions={...state.permissions,...p};render();return true;}catch{return false;}}
function snapshotFormState(){const root=document.querySelector('#main');if(!root)return null;const fields=[...root.querySelectorAll('input,select,textarea')].map((el,i)=>({key:el.id||el.name||('__idx_'+i),tag:el.tagName,type:el.type||'',value:el.value,checked:!!el.checked,selectedIndex:el.selectedIndex}));const active=document.activeElement;return {fields,activeKey:active?(active.id||active.name||null):null,selection:active&&typeof active.selectionStart==='number'?{start:active.selectionStart,end:active.selectionEnd}:null};}
function restoreFormState(s){if(!s)return;const root=document.querySelector('#main');if(!root)return;const all=[...root.querySelectorAll('input,select,textarea')];s.fields.forEach((x,i)=>{let el=x.key?root.querySelector('#'+CSS.escape(x.key)):null;if(!el)el=all[i];if(!el)return;if(el.type==='checkbox'||el.type==='radio')el.checked=x.checked;else el.value=x.value;if(el.tagName==='SELECT'&&x.selectedIndex>=0)el.selectedIndex=x.selectedIndex;});if(s.activeKey){const el=root.querySelector('#'+CSS.escape(s.activeKey))||root.querySelector('[name="'+CSS.escape(s.activeKey)+'"]');if(el){el.focus({preventScroll:true});if(s.selection&&typeof el.setSelectionRange==='function'){try{el.setSelectionRange(s.selection.start,s.selection.end)}catch(e){}}}}}
async function refreshData(manual=false){if(!state.user||state.syncing)return;state.syncing=true;const formState=snapshotFormState();try{portalData=loadData();const url=(localStorage.getItem(STORAGE_API)||'').trim();if(url){const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const json=await res.json();portalData={separacoes:Array.isArray(json.separacoes)?json.separacoes:portalData.separacoes,carregamentos:Array.isArray(json.carregamentos)?json.carregamentos:portalData.carregamentos,atividades:Array.isArray(json.atividades)?json.atividades:portalData.atividades,conferencias:Array.isArray(json.conferencias)?json.conferencias:portalData.conferencias};saveData();}state.lastSync=Date.now();if(state.user)render();restoreFormState(formState);if(manual)showToast('Informações atualizadas sem perder os dados digitados.');}catch(e){state.lastSync=Date.now();if(state.user){render();restoreFormState(formState);}if(manual)showToast('Dados locais atualizados; API não disponível.');}finally{state.syncing=false;}}
function clock(){const e=document.querySelector('#clock');if(e)e.textContent=new Date().toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});}
document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#menuBtn')?.addEventListener('click',()=>{document.querySelector('#sidebar')?.classList.add('open');document.querySelector('#overlay')?.classList.add('show');});document.querySelector('#overlay')?.addEventListener('click',closeMenu);document.querySelector('#profileBtn')?.addEventListener('click',()=>{state.page='perfil';render();});setInterval(clock,1000);clock();if(!restoreSession()){document.querySelector('#login')?.classList.remove('hide');document.querySelector('#app')?.classList.add('hide');}setInterval(()=>refreshData(false),10000);});

/* SIGA 3.0 user management patch */
function navItems(){return [['home','⌂','Início',true],['separacoes','▣','Minhas Separações',state.permissions.separacoes],['carregamentos','▰','Meus Carregamentos',state.permissions.carregamentos],['conferencias','✓','Minhas Conferências',state.permissions.conferencias],['atividades','◷','Minhas Atividades',state.permissions.atividades],['desempenho','▥','Meu Desempenho',state.permissions.desempenho],['perfil','●','Perfil / Acesso',true],['admin','⚙','Cadastrar Usuários',state.permissions.admin],['logout','↪','Sair',true]];}
const USER_STORE='siga30_portal_users_v3';
try{const saved=JSON.parse(localStorage.getItem(USER_STORE)||'null');if(Array.isArray(saved)){users.splice(0,users.length,...saved);}}catch(e){}
function adminPage(){return '<div class="page-title"><h1>Cadastrar Usuários</h1><p>Autor / Administrador • cadastre, edite e controle as permissões individualmente.</p></div><div class="admin-grid"><div class="panel"><div class="panel-title"><div><h3>👤 Usuários cadastrados</h3><div class="sub">Crie novos acessos ou edite os existentes.</div></div><button class="btn" onclick="openUserForm()">+ Novo usuário</button></div><div id="userList" class="user-list" style="margin-top:12px"></div></div><div class="panel" id="userFormPanel"><h3 id="userFormTitle">🔐 Novo usuário</h3><form id="userForm" onsubmit="saveUser(event)"><input type="hidden" id="editUserId"><div class="user-form" style="margin-top:12px"><div class="field"><label>Nome completo<input id="newName" required></label></div><div class="field"><label>Usuário<input id="newLogin" required></label></div><div class="field"><label>Senha<input id="newPassword" type="password"></label></div><div class="field"><label>Perfil<select id="newRole"><option>Operador</option><option>Conferente</option><option>Operador + Conferente</option><option>Administrador</option></select></label></div></div><h3 style="margin-top:14px">Liberar funções</h3><div class="checkgrid"><label class="check"><input id="pSep" type="checkbox"> Minhas Separações</label><label class="check"><input id="pCar" type="checkbox"> Meus Carregamentos</label><label class="check"><input id="pAct" type="checkbox"> Minhas Atividades</label><label class="check"><input id="pDes" type="checkbox"> Meu Desempenho</label><label class="check"><input id="pConf" type="checkbox"> Minhas Conferências</label></div><div class="form-actions"><button class="btn" type="submit">Salvar usuário</button><button class="btn secondary" type="button" onclick="openUserForm()">Limpar</button></div></form></div></div>';}
function renderUsers(){const el=document.querySelector('#userList');if(!el)return;el.innerHTML=users.map((u,i)=>'<div class="user-row"><div class="avatar">'+esc(u[0])+'</div><div><b>'+esc(u[1])+'</b><small>'+esc(u[2])+' • '+esc(u[3])+'</small></div><button class="btn secondary" onclick="editUser('+i+')">Editar</button></div>').join('');}
function openUserForm(){const f=document.querySelector('#userForm');if(!f)return;f.reset();document.querySelector('#editUserId').value='';document.querySelector('#userFormTitle').textContent='🔐 Novo usuário';document.querySelector('#newLogin').disabled=false;document.querySelector('#newPassword').required=false;}
function editUser(i){const u=users[i];if(!u)return;document.querySelector('#editUserId').value=i;document.querySelector('#newName').value=u[1]||'';document.querySelector('#newLogin').value=(u[1]||'').toLowerCase().replace(/[^a-z0-9]+/g,'.').replace(/^\.|\.$/g,'');document.querySelector('#newLogin').disabled=true;document.querySelector('#newPassword').value='';document.querySelector('#newPassword').required=false;document.querySelector('#newRole').value=u[2]||'Operador';const s=u[3]||'';document.querySelector('#pSep').checked=/separa/i.test(s)||/todas/i.test(s);document.querySelector('#pCar').checked=/carreg/i.test(s)||/todas/i.test(s);document.querySelector('#pAct').checked=/ativ/i.test(s)||/todas/i.test(s);document.querySelector('#pDes').checked=/desempenho/i.test(s)||/todas/i.test(s);document.querySelector('#pConf').checked=/confer/i.test(s)||/todas/i.test(s);document.querySelector('#userFormTitle').textContent='✏️ Editar usuário';document.querySelector('#userFormPanel')?.scrollIntoView({behavior:'smooth',block:'start'});}
function saveUser(ev){ev.preventDefault();const idx=document.querySelector('#editUserId').value;const name=document.querySelector('#newName').value.trim();const login=document.querySelector('#newLogin').value.trim();if(!name||!login){showToast('Preencha nome e usuário');return;}const role=document.querySelector('#newRole').value;const perms=[];if(document.querySelector('#pSep').checked)perms.push('Separação');if(document.querySelector('#pCar').checked)perms.push('Carregamento');if(document.querySelector('#pAct').checked)perms.push('Atividades');if(document.querySelector('#pDes').checked)perms.push('Desempenho');if(document.querySelector('#pConf').checked)perms.push('Conferência');const avatar=(name.split(/\s+/).map(x=>x[0]).join('').slice(0,2)||'US').toUpperCase();const item=[avatar,name,role,perms.length?perms.join(' • '):'Nenhuma função'];if(idx==='')users.push(item);else users[Number(idx)]=item;localStorage.setItem(USER_STORE,JSON.stringify(users));showToast(idx===''?'Novo usuário cadastrado':'Usuário atualizado');state.page='admin';render();}
const oldRender=render;render=function(){oldRender();if(state.page==='admin')renderUsers();};

/* ===== SIGA 3.0 UX / OPERATIONS UPGRADE ===== */
const ACCOUNT_STORE='siga30_accounts_v4';
const NOTIFY_STORE='siga30_notifications_v1';
function normalizeAccount(x){if(!x)return null;if(Array.isArray(x)){const d=x[3]||'';return {id:(x[1]||'').toLowerCase(),name:x[1]||'',password:'',role:x[2]||'Operador',cd:'CDD',permissions:{separacoes:/separa/i.test(d)||/todas/i.test(d),carregamentos:/carreg/i.test(d)||/todas/i.test(d),atividades:/ativ/i.test(d)||/todas/i.test(d),desempenho:/desempenho/i.test(d)||/todas/i.test(d),conferencias:/confer/i.test(d)||/todas/i.test(d),admin:/administrador|autor/i.test(x[2]||'')}};}return {...x,permissions:{...x.permissions}};}
function accountList(){try{const raw=JSON.parse(localStorage.getItem(ACCOUNT_STORE)||'null');if(Array.isArray(raw)&&raw.length)return raw.map(normalizeAccount);}catch(e){}return [{id:'01022005',name:'Marco',password:'01022005',role:'Autor / Administrador',cd:'CDD',permissions:{separacoes:true,carregamentos:true,atividades:true,desempenho:true,conferencias:true,admin:true}},{id:'joao.silva',name:'João Silva',password:'1234',role:'Operador',cd:'CDD',permissions:{separacoes:true,carregamentos:true,atividades:true,desempenho:true,conferencias:false,admin:false}}];}
function saveAccounts(a){localStorage.setItem(ACCOUNT_STORE,JSON.stringify(a));}
function getNotifications(){try{const n=JSON.parse(localStorage.getItem(NOTIFY_STORE)||'null');return Array.isArray(n)?n:[];}catch(e){return [];}}
function saveNotifications(n){localStorage.setItem(NOTIFY_STORE,JSON.stringify(n));}
function seedNotifications(){if(!getNotifications().length)saveNotifications([{id:1,title:'Portal pronto',text:'Seu painel operacional está atualizado.',time:new Date().toISOString(),read:false,type:'info'},{id:2,title:'Atenção operacional',text:'Confira as atividades pendentes do dia.',time:new Date().toISOString(),read:false,type:'warning'}]);}
function unreadNotifications(){return getNotifications().filter(x=>!x.read).length;}
function addNotification(title,text,type='info'){const n=getNotifications();n.unshift({id:Date.now(),title,text,time:new Date().toISOString(),read:false,type});saveNotifications(n.slice(0,50));}
function notificationPanel(){const n=getNotifications();return '<div class="notify-panel" id="notifyPanel"><div class="notify-head"><b>Notificações</b><button class="btn secondary" onclick="markNotificationsRead()">Marcar como lidas</button></div>'+(n.length?n.slice(0,8).map(x=>'<div class="notify-item '+(x.read?'read':'unread')+'"><span class="notify-dot '+esc(x.type||'info')+'"></span><div><b>'+esc(x.title)+'</b><p>'+esc(x.text)+'</p><small>'+esc(new Date(x.time).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}))+'</small></div></div>').join(''):'<div class="empty">Nenhuma notificação.</div>')+'</div>';}
function toggleNotifications(){document.querySelector('#notifyPanel')?.classList.toggle('show');}
function markNotificationsRead(){saveNotifications(getNotifications().map(x=>({...x,read:true})));renderHeaderExtras();}
function renderHeaderExtras(){const h=document.querySelector('header');if(!h)return;let box=document.querySelector('#headerNotify');if(!box){box=document.createElement('div');box.id='headerNotify';box.className='header-actions';h.appendChild(box);}box.innerHTML='<button class="notify-btn" onclick="toggleNotifications()" aria-label="Notificações">◉'+(unreadNotifications()?'<em>'+unreadNotifications()+'</em>':'')+'</button>'+notificationPanel();}
function voiceCommand(){const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){showToast('Comando de voz não disponível neste navegador.');return;}const r=new Speech();r.lang='pt-BR';r.interimResults=false;r.maxAlternatives=1;showToast('🎙️ Fale um comando...');r.onresult=e=>{const q=norm(e.results[0][0].transcript);const map=[['separa','separacoes'],['carreg','carregamentos'],['confer','conferencias'],['atividade','atividades'],['desempenho','desempenho'],['perfil','perfil'],['usuário','admin'],['usuario','admin']];const m=map.find(x=>q.includes(x[0]));if(!m){showToast('Comando não reconhecido.');return;}state.page=m[1];render();};r.onerror=()=>showToast('Não foi possível reconhecer o comando.');r.start();}
function securePermission(page){const map={separacoes:'separacoes',carregamentos:'carregamentos',conferencias:'conferencias',atividades:'atividades',desempenho:'desempenho',admin:'admin'};return !map[page]||!!state.permissions[map[page]];}
function render(){if(!state.user)return;if(!securePermission(state.page)){state.page='home';showToast('Você não possui permissão para esta área.');}document.querySelector('#login')?.classList.add('hide');document.querySelector('#app')?.classList.remove('hide');updateUserUI();renderNav();const pages={home,separacoes:separacoesPage,carregamentos:carregamentosPage,conferencias:conferenciasPage,atividades:atividadesPage,desempenho:desempenhoPage,perfil:perfilPage,admin:adminPage};const main=document.querySelector('#main');if(main)main.innerHTML=(pages[state.page]||home)();closeMenu();renderHeaderExtras();headerClock();if(state.page==='admin')renderUsers();}
function headerClock(){const h=document.querySelector('header');if(!h)return;let c=document.querySelector('#headerClock');if(!c){c=document.createElement('small');c.id='headerClock';c.className='header-clock';h.insertBefore(c,h.querySelector('.who'));}c.textContent=new Date().toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});}
function home(){const t=totals(),acts=userActs(),pending=acts.filter(x=>/andamento|pendente/i.test(x.status||'')).length;return '<div class="hero"><div><div class="eyebrow">Painel operacional • '+new Date().toLocaleDateString('pt-BR')+'</div><h1>Olá, '+esc((state.user.name||'Usuário').split(' ')[0])+'!</h1><p>Visão rápida das suas atividades, resultados e pendências.</p></div><div class="hero-actions"><button class="btn secondary" onclick="voiceCommand()">🎙️ Comando de voz</button><button class="btn secondary" onclick="refreshData(true)">↻ Atualizar agora</button></div></div><div class="cards"><div class="stat blue"><div class="stat-top"><span>SEPARAÇÕES</span><span class="stat-icon">▣</span></div><strong>'+t.s+'</strong><small>Hoje</small></div><div class="stat green"><div class="stat-top"><span>CARREGAMENTOS</span><span class="stat-icon">▰</span></div><strong>'+t.c+'</strong><small>Hoje</small></div><div class="stat purple"><div class="stat-top"><span>CONFERÊNCIAS</span><span class="stat-icon">✓</span></div><strong>'+t.f+'</strong><small>Hoje</small></div><div class="stat dark"><div class="stat-top"><span>ATIVIDADES</span><span class="stat-icon">☷</span></div><strong>'+t.a+'</strong><small>'+pending+' pendente(s)</small></div></div><div class="operational-strip"><div><span>STATUS</span><b>● Online</b></div><div><span>RESULTADOS OK</span><b>'+(t.fok+t.cok)+'</b></div><div><span>NÃO OK</span><b class="badtext">'+(t.fbad+t.cbad)+'</b></div><div><span>ATUALIZAÇÃO</span><b>'+(state.lastSync?new Date(state.lastSync).toLocaleTimeString('pt-BR'):'agora')+'</b></div></div><div class="grid2"><div class="panel"><div class="panel-title"><div><h3>📋 Atividades feitas hoje</h3><div class="sub">Linha do tempo individual • descrição original preservada</div></div><button class="btn secondary" onclick="state.page=\'atividades\';render()">Ver todas →</button></div><div class="timeline">'+(acts.length?acts.slice(0,10).map(e=>'<div class="event"><span class="dot"></span><div><b>'+esc(e.hora||e.inicio||'')+' • '+esc(e.tipo||'Atividade')+'</b><small>'+esc(e.descricao_original||e.descricao||e.atividade||e.texto||'')+'</small></div>'+badge(e.status||'PENDENTE',resultClass(e.status))+'</div>').join(''):'<div class="empty">Nenhuma atividade registrada.</div>')+'</div></div><div><div class="panel"><h3>📊 Atividades de hoje</h3><div class="sub">Volume de operações por categoria</div>'+bar('Separações',t.s,Math.max(t.s,t.c,t.f,t.a,1),'')+bar('Carregamentos',t.c,Math.max(t.s,t.c,t.f,t.a,1),'green')+bar('Conferências',t.f,Math.max(t.s,t.c,t.f,t.a,1),'purple')+bar('Atividades',t.a,Math.max(t.s,t.c,t.f,t.a,1),'dark')+'</div><div class="panel"><h3>📈 Resultados das operações</h3><div class="sub">OK e NÃO OK registrados</div>'+bar('Conferências OK',t.fok,Math.max(t.f,1),'green')+bar('Conferências NÃO OK',t.fbad,Math.max(t.f,1),'red')+bar('Carregamentos OK',t.cok,Math.max(t.c,1),'green')+bar('Carregamentos NÃO OK',t.cbad,Math.max(t.c,1),'red')+'</div></div></div>';}
function desempenhoPage(){const t=totals(),max=Math.max(t.s,t.c,t.f,t.a,1),ok=t.fok+t.cok,bad=t.fbad+t.cbad,total=ok+bad,rate=total?Math.round(ok/total*100):0;return '<div class="page-title"><h1>Meu Desempenho</h1><p>Indicadores operacionais do usuário no período disponível.</p></div><div class="performance-kpis"><div class="perf-kpi"><span>Taxa de conformidade</span><strong>'+rate+'%</strong><small>'+ok+' OK de '+total+' resultados</small></div><div class="perf-kpi"><span>Total de operações</span><strong>'+(t.s+t.c+t.f)+'</strong><small>Separações + carregamentos + conferências</small></div><div class="perf-kpi"><span>Atividades</span><strong>'+t.a+'</strong><small>Registros vinculados</small></div><div class="perf-kpi"><span>Ocorrências</span><strong>'+bad+'</strong><small>Resultados NÃO OK</small></div></div><div class="grid2"><div class="panel"><h3>Produção operacional</h3><div class="sub">Comparação das atividades registradas</div>'+bar('Separações',t.s,max,'')+bar('Carregamentos',t.c,max,'green')+bar('Conferências',t.f,max,'purple')+bar('Atividades',t.a,max,'dark')+'</div><div class="panel"><h3>Qualidade operacional</h3><div class="sub">Resultados registrados</div>'+bar('Conferências OK',t.fok,Math.max(t.f,1),'green')+bar('Conferências NÃO OK',t.fbad,Math.max(t.f,1),'red')+bar('Carregamentos OK',t.cok,Math.max(t.c,1),'green')+bar('Carregamentos NÃO OK',t.cbad,Math.max(t.c,1),'red')+'</div></div><div class="panel performance-note"><b>Leitura</b><span>A taxa considera somente resultados OK/NÃO OK registrados; atividades sem resultado ficam fora do cálculo.</span></div>';}
function adminPage(){return '<div class="page-title"><h1>Cadastrar Usuários</h1><p>Autor / Administrador • cadastro, edição e permissões individuais.</p></div><div class="admin-grid"><div class="panel"><div class="panel-title"><div><h3>👤 Usuários cadastrados</h3><div class="sub">Acesso por perfil e função</div></div><button class="btn" onclick="openUserForm()">+ Novo usuário</button></div><div id="userList" class="user-list" style="margin-top:12px"></div></div><div class="panel" id="userFormPanel"><h3 id="userFormTitle">🔐 Novo usuário</h3><form id="userForm" onsubmit="saveUser(event)"><input type="hidden" id="editUserId"><div class="user-form" style="margin-top:12px"><div class="field"><label>Nome completo<input id="newName" required></label></div><div class="field"><label>Usuário<input id="newLogin" required></label></div><div class="field"><label>Senha<input id="newPassword" type="password" minlength="4"></label></div><div class="field"><label>Filial<input id="newCd" value="CDD"></label></div><div class="field"><label>Perfil<select id="newRole"><option>Operador</option><option>Conferente</option><option>Operador + Conferente</option><option>Administrador</option></select></label></div></div><h3 style="margin-top:14px">Liberar funções</h3><div class="checkgrid"><label class="check"><input id="pSep" type="checkbox"> Minhas Separações</label><label class="check"><input id="pCar" type="checkbox"> Meus Carregamentos</label><label class="check"><input id="pAct" type="checkbox"> Minhas Atividades</label><label class="check"><input id="pDes" type="checkbox"> Meu Desempenho</label><label class="check"><input id="pConf" type="checkbox"> Minhas Conferências</label></div><div class="admin-note">As funções são independentes. Um conferente também pode receber acesso a separações, carregamentos ou desempenho.</div><div class="form-actions"><button class="btn" type="submit">Salvar usuário</button><button class="btn secondary" type="button" onclick="openUserForm()">Limpar</button></div></form></div></div>';}
function renderUsers(){const el=document.querySelector('#userList');if(!el)return;const a=accountList();el.innerHTML=a.map((u,i)=>'<div class="user-row"><div class="avatar">'+esc((u.name||'US').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase())+'</div><div><b>'+esc(u.name)+'</b><small>'+esc(u.role)+' • '+esc(u.cd||'CDD')+' • '+Object.entries(u.permissions||{}).filter(([k,v])=>v&&k!=='admin').map(([k])=>k).join(', ')+'</small></div><button class="btn secondary" onclick="editUser('+i+')">Editar</button></div>').join('');}
function openUserForm(){const f=document.querySelector('#userForm');if(!f)return;f.reset();document.querySelector('#editUserId').value='';document.querySelector('#userFormTitle').textContent='🔐 Novo usuário';document.querySelector('#newLogin').disabled=false;document.querySelector('#newPassword').required=true;document.querySelector('#newCd').value='CDD';}
function editUser(i){const a=accountList(),u=a[i];if(!u)return;document.querySelector('#editUserId').value=i;document.querySelector('#newName').value=u.name||'';document.querySelector('#newLogin').value=u.id||'';document.querySelector('#newLogin').disabled=true;document.querySelector('#newPassword').value='';document.querySelector('#newPassword').required=false;document.querySelector('#newCd').value=u.cd||'CDD';document.querySelector('#newRole').value=u.role||'Operador';const p=u.permissions||{};document.querySelector('#pSep').checked=!!p.separacoes;document.querySelector('#pCar').checked=!!p.carregamentos;document.querySelector('#pAct').checked=!!p.atividades;document.querySelector('#pDes').checked=!!p.desempenho;document.querySelector('#pConf').checked=!!p.conferencias;document.querySelector('#userFormTitle').textContent='✏️ Editar usuário';document.querySelector('#userFormPanel')?.scrollIntoView({behavior:'smooth',block:'start'});}
function saveUser(ev){ev.preventDefault();let a=accountList(),idx=document.querySelector('#editUserId').value,name=document.querySelector('#newName').value.trim(),id=document.querySelector('#newLogin').value.trim().toLowerCase(),pw=document.querySelector('#newPassword').value;if(!name||!id||(idx===''&&!pw)){showToast('Preencha nome, usuário e senha.');return;}if(idx===''&&a.some(x=>x.id===id)){showToast('Esse usuário já existe.');return;}const old=idx===''?null:a[Number(idx)],role=document.querySelector('#newRole').value,cd=document.querySelector('#newCd').value.trim()||'CDD';const item={id,name,password:pw||old?.password||'',role,cd,permissions:{separacoes:!!document.querySelector('#pSep').checked,carregamentos:!!document.querySelector('#pCar').checked,atividades:!!document.querySelector('#pAct').checked,desempenho:!!document.querySelector('#pDes').checked,conferencias:!!document.querySelector('#pConf').checked,admin:/administrador/i.test(role)}};if(idx==='')a.push(item);else a[Number(idx)]=item;saveAccounts(a);addNotification('Acesso atualizado',name+' teve suas permissões configuradas.');showToast(idx===''?'Usuário cadastrado com sucesso':'Usuário atualizado com sucesso');state.page='admin';render();}
function login(){const id=(document.querySelector('#u')?.value||'').trim().toLowerCase(),pw=document.querySelector('#pw')?.value||'',msg=document.querySelector('#loginmsg');const u=accountList().find(x=>x.id===id);if(!id||!pw){if(msg)msg.textContent='Informe usuário e senha.';return;}if(!u||u.password!==pw){if(msg)msg.textContent='Usuário ou senha inválidos.';return;}state.user={id:u.id,usuario:u.id,username:u.id,name:u.name,role:u.role,cd:u.cd||'CDD',avatar:(u.name||'US').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()};state.permissions={...state.permissions,...u.permissions};localStorage.setItem(STORAGE_USER,JSON.stringify(state.user));localStorage.setItem('siga30_portal_permissions_v2',JSON.stringify(state.permissions));seedNotifications();state.page='home';render();refreshData(true);}
function restoreSession(){try{const u=JSON.parse(localStorage.getItem(STORAGE_USER)||'null');if(!u)return false;const a=accountList().find(x=>x.id===u.id);if(!a)return false;state.user=u;state.permissions={...state.permissions,...a.permissions};render();return true;}catch{return false;}}
