const STORAGE_USER='siga30_portal_user_v2';
const STORAGE_DATA='siga30_portal_data_v2';
const STORAGE_API='siga30_portal_api_v1';

const state={
  user:null,
  permissions:{separacoes:true,carregamentos:true,atividades:true,desempenho:true,conferencias:false,admin:false},
  page:'home',
  lastSync:null,
  syncing:false
};

const sampleSeps=[
 {lote:'LT-1025',pedido:'PED-4587',destino:'Ponte Nova',peso:'860 kg',volumes:'42',inicio:'08:15',fim:'09:02',status:'Finalizada',resultado:'OK',usuario_id:'joao.silva'},
 {lote:'LT-1038',pedido:'PED-4621',destino:'Viçosa',peso:'620 kg',volumes:'31',inicio:'10:20',fim:'11:10',status:'Em andamento',resultado:'',usuario_id:'joao.silva'},
 {lote:'LT-1029',pedido:'PED-4601',destino:'Ubá',peso:'740 kg',volumes:'38',inicio:'11:45',fim:'12:30',status:'Finalizada',resultado:'OK',usuario_id:'joao.silva'},
 {lote:'LT-1030',pedido:'PED-4590',destino:'Rio Casca',peso:'510 kg',volumes:'25',inicio:'13:12',fim:'14:05',status:'Finalizada',resultado:'OK',usuario_id:'joao.silva'},
 {lote:'LT-1018',pedido:'PED-4560',destino:'Mariana',peso:'380 kg',volumes:'18',inicio:'15:20',fim:'16:10',status:'Pendente',resultado:'',usuario_id:'joao.silva'}
];
const sampleCars=[
 {romaneio:'ROM-783',destino:'Ponte Nova',motorista:'João Silva',placa:'OFA-4452',peso:'12.500 kg',volumes:'48',inicio:'10:20',fim:'12:05',resultado:'OK',status:'Finalizado',usuario_id:'joao.silva'},
 {romaneio:'ROM-782',destino:'Ubá',motorista:'Carlos Lima',placa:'OQP-9621',peso:'8.600 kg',volumes:'36',inicio:'11:20',fim:'12:06',resultado:'OK',status:'Finalizado',usuario_id:'joao.silva'},
 {romaneio:'ROM-781',destino:'Rio Casca',motorista:'Pedro Alves',placa:'HKG-7810',peso:'7.400 kg',volumes:'28',inicio:'09:10',fim:'11:00',resultado:'NÃO OK',status:'Finalizado',usuario_id:'joao.silva'},
 {romaneio:'ROM-780',destino:'Mariana',motorista:'Rafael Souza',placa:'KBS-2055',peso:'5.400 kg',volumes:'20',inicio:'08:10',fim:'09:50',resultado:'OK',status:'Finalizado',usuario_id:'joao.silva'}
];
const sampleActs=[
 {hora:'08:15',tipo:'Separação',descricao_original:'Início da separação • LT-1025 • Ponte Nova',status:'Em andamento',usuario_id:'joao.silva'},
 {hora:'09:02',tipo:'Separação',descricao_original:'Separação finalizada • LT-1025',status:'Finalizada',usuario_id:'joao.silva'},
 {hora:'09:10',tipo:'Conferência',descricao_original:'Conferência • PED-4587',status:'OK',usuario_id:'joao.silva'},
 {hora:'10:20',tipo:'Carregamento',descricao_original:'Início do carregamento • ROM-783 • Viçosa',status:'Em andamento',usuario_id:'joao.silva'},
 {hora:'11:05',tipo:'Carregamento',descricao_original:'Carregamento finalizado • ROM-783',status:'OK',usuario_id:'joao.silva'},
 {hora:'12:15',tipo:'Conferência',descricao_original:'Conferência • PED-4612 • 3 volumes divergentes',status:'NÃO OK',usuario_id:'joao.silva'},
 {hora:'13:30',tipo:'Carregamento',descricao_original:'Carregamento finalizado • ROM-785 • 2 volumes divergentes',status:'NÃO OK',usuario_id:'joao.silva'}
];
const sampleConfs=[
 {operacao:'Separação',referencia:'PED-4587',hora:'09:10',resultado:'OK',ocorrencia:'—',quantidade_divergente:'—',observacao:'—',usuario_id:'joao.silva'},
 {operacao:'Separação',referencia:'LT-1025',hora:'10:45',resultado:'OK',ocorrencia:'—',quantidade_divergente:'—',observacao:'—',usuario_id:'joao.silva'},
 {operacao:'Carregamento',referencia:'ROM-783',hora:'12:15',resultado:'OK',ocorrencia:'—',quantidade_divergente:'—',observacao:'—',usuario_id:'joao.silva'},
 {operacao:'Conferência',referencia:'PED-4612',hora:'12:15',resultado:'NÃO OK',ocorrencia:'3 volumes',quantidade_divergente:'3',observacao:'Volumes faltantes',usuario_id:'joao.silva'},
 {operacao:'Carregamento',referencia:'ROM-785',hora:'13:30',resultado:'NÃO OK',ocorrencia:'2 volumes',quantidade_divergente:'2',observacao:'Volumes a menos',usuario_id:'joao.silva'}
];
const users=[['JS','João Silva','Operador','Separação • Carregamento • Atividades'],['CS','Carlos Souza','Conferente','Conferência • Atividades'],['PA','Pedro Alves','Operador + Conferente','Todas as funções'],['RM','Rafael Mendes','Operador','Separação • Atividades']];

let portalData=loadData();
function loadData(){
 try{const x=JSON.parse(localStorage.getItem(STORAGE_DATA)||'null');return {separacoes:Array.isArray(x?.separacoes)?x.separacoes:sampleSeps,carregamentos:Array.isArray(x?.carregamentos)?x.carregamentos:sampleCars,atividades:Array.isArray(x?.atividades)?x.atividades:sampleActs,conferencias:Array.isArray(x?.conferencias)?x.conferencias:sampleConfs};}
 catch{return {separacoes:sampleSeps,carregamentos:sampleCars,atividades:sampleActs,conferencias:sampleConfs};}
}
function saveData(){localStorage.setItem(STORAGE_DATA,JSON.stringify(portalData));}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function norm(v){return String(v??'').trim().toLowerCase();}
function sameUser(o){
 const u=state.user||{}; const ids=[o.usuario_id,o.user_id,o.operador_id,o.conferente_id,o.usuario,o.operador,o.conferente].filter(Boolean).map(norm);
 const names=[u.id,u.usuario,u.username,u.login,u.name,u.nome].filter(Boolean).map(norm);
 if(!ids.length)return true;
 return ids.some(id=>names.includes(id)||names.some(n=>id===n));
}
function resultClass(v){const x=norm(v);return x==='ok'||x==='finalizada'||x==='finalizado'?'ok':x.includes('não ok')||x.includes('nao ok')?'bad':'pending';}
function badge(t,c){return `<span class="badge ${c||resultClass(t)}">${esc(t)}</span>`;}
function bar(label,value,max,cls=''){const pct=max?Math.min(100,Math.round(value/max*100)):0;return `<div class="bar-row"><label>${esc(label)}</label><div class="bar"><div class="fill ${cls}" style="width:${pct}%"></div></div><strong>${value}</strong></div>`;}
function tablePage(title,sub,heads,rows){return `<div class="page-title"><h1>${esc(title)}</h1><p>${esc(sub)}</p></div><div class="panel"><div class="filters"><input placeholder="Pesquisar..." oninput="filterRows(this.value)"><select id="periodFilter"><option>Hoje</option><option>Últimos 7 dias</option><option>Este mês</option></select><select id="statusFilter"><option>Todos os status</option><option>Finalizada</option><option>Em andamento</option><option>OK</option><option>NÃO OK</option></select><button class="btn" onclick="applyFilters()">Filtrar</button></div><div class="table-wrap"><table class="table"><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody id="dataRows">${rows||'<tr><td colspan="20" class="empty">Nenhum registro encontrado.</td></tr>'}</tbody></table></div></div>`;}
function userSeps(){return portalData.separacoes.filter(sameUser);}
function userCars(){return portalData.carregamentos.filter(sameUser);}
function userActs(){return portalData.atividades.filter(sameUser);}
function userConfs(){return portalData.conferencias.filter(sameUser);}
function totals(){const s=userSeps(),c=userCars(),f=userConfs(),a=userActs();return {s:s.length,c:c.length,f:f.length,a:a.length,fok:f.filter(x=>norm(x.resultado)==='ok').length,fbad:f.filter(x=>norm(x.resultado).includes('não ok')||norm(x.resultado).includes('nao ok')).length,cok:c.filter(x=>norm(x.resultado)==='ok').length,cbad:c.filter(x=>norm(x.resultado).includes('não ok')||norm(x.resultado).includes('nao ok')).length};}
function navItems(){return [['home','⌂','Início',true],['separacoes','▣','Minhas Separações',state.permissions.separacoes],['carregamentos','▰','Meus Carregamentos',state.permissions.carregamentos],['conferencias','✓','Minhas Conferências',state.permissions.conferencias],['atividades','◷','Minhas Atividades',state.permissions.atividades],['desempenho','▥','Meu Desempenho',state.permissions.desempenho],['perfil','●','Perfil / Acesso',true],['admin','⚙','Gestão de Usuários',state.permissions.admin],['logout','↪','Sair',true]];}
function renderNav(){const el=document.querySelector('#nav');if(!el)return;el.innerHTML=navItems().filter(x=>x[3]).map(x=>`<button class="nav-item ${state.page===x[0]?'active':''}" data-page="${x[0]}"><span class="nav-icon">${x[1]}</span>${esc(x[2])}</button>`).join('');el.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{const p=b.dataset.page;if(p==='logout'){logout();return;}state.page=p;render();});}
function updateUserUI(){if(!state.user)return;const n=state.user.name||state.user.nome||'Usuário';const initials=(state.user.avatar||n.split(/\s+/).map(x=>x[0]).join('').slice(0,2)).toUpperCase();['sideInitials','headerInitials'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=initials;});const sn=document.getElementById('sideName');if(sn)sn.textContent=n;const sr=document.getElementById('sideRole');if(sr)sr.textContent=state.user.role||'Operador';const hw=document.getElementById('headerWho');if(hw)hw.textContent=`${state.user.cd||'CDD'} · ${n}`;}
function render(){if(!state.user)return;document.querySelector('#login')?.classList.add('hide');document.querySelector('#app')?.classList.remove('hide');updateUserUI();renderNav();const pages={home,separacoes:separacoesPage,carregamentos:carregamentosPage,conferencias:conferenciasPage,atividades:atividadesPage,desempenho:desempenhoPage,perfil:perfilPage,admin:adminPage};const main=document.querySelector('#main');if(main)main.innerHTML=(pages[state.page]||home)();closeMenu();}
function home(){const t=totals();const acts=userActs();return `<div class="hero"><div><div class="eyebrow">Painel do usuário</div><h1>Olá, ${esc((state.user.name||'Usuário').split(' ')[0])}!</h1><p>Aqui está o resumo das suas atividades de hoje.</p></div><button class="btn secondary" onclick="refreshData(true)">↻ Atualizar agora</button></div><div class="cards"><div class="stat blue"><div class="stat-top"><span>SEPARAÇÕES</span><span class="stat-icon">▣</span></div><strong>${t.s}</strong><small>Hoje</small></div><div class="stat green"><div class="stat-top"><span>CARREGAMENTOS</span><span class="stat-icon">▰</span></div><strong>${t.c}</strong><small>Hoje</small></div><div class="stat purple"><div class="stat-top"><span>CONFERÊNCIAS</span><span class="stat-icon">✓</span></div><strong>${t.f}</strong><small>Hoje</small></div><div class="stat dark"><div class="stat-top"><span>ATIVIDADES</span><span class="stat-icon">☷</span></div><strong>${t.a}</strong><small>Hoje</small></div></div><div class="grid2"><div class="panel"><div class="panel-title"><div><h3>📋 Atividades feitas hoje</h3><div class="sub">Registro individual do usuário</div></div><button class="btn secondary" onclick="state.page='atividades';render()">Ver todas →</button></div><div class="timeline">${acts.length?acts.map(e=>`<div class="event"><span class="dot"></span><div><b>${esc(e.hora||e.inicio||'')} • ${esc(e.tipo||'Atividade')}</b><small>${esc(e.descricao_original||e.descricao||e.atividade||e.texto||'')}</small></div>${badge(e.status||'PENDENTE',resultClass(e.status))}</div>`).join(''):'<div class="empty">Nenhuma atividade registrada.</div>'}</div></div><div><div class="panel"><h3>📊 Atividades de hoje</h3><div class="sub">Gráfico horizontal</div>${bar('Separações',t.s,Math.max(t.s,t.c,t.f,t.a,1),'')}${bar('Carregamentos',t.c,Math.max(t.s,t.c,t.f,t.a,1),'green')}${bar('Conferências',t.f,Math.max(t.s,t.c,t.f,t.a,1),'purple')}${bar('Atividades',t.a,Math.max(t.s,t.c,t.f,t.a,1),'dark')}</div><div class="panel"><h3>📈 Resultados das operações</h3><div class="sub">OK e NÃO OK</div>${bar('Conferências OK',t.fok,Math.max(t.f,1),'green')}${bar('Conferências NÃO OK',t.fbad,Math.max(t.f,1),'red')}${bar('Carregamentos OK',t.cok,Math.max(t.c,1),'green')}${bar('Carregamentos NÃO OK',t.cbad,Math.max(t.c,1),'red')}</div></div></div><div class="sub" style="margin-top:10px">Última atualização: ${esc(state.lastSync?new Date(state.lastSync).toLocaleTimeString('pt-BR'):'agora')}</div>`;}
function separacoesPage(){const d=userSeps();return tablePage('Minhas Separações','Apenas separações vinculadas ao seu usuário.',['Lote','Pedido','Destino','Peso','Volumes','Início','Fim','Status',''],d.map(r=>`<tr><td>${esc(r.lote||r.numero_lote)}</td><td>${esc(r.pedido||r.numero_pedido)}</td><td>${esc(r.destino||r.rota)}</td><td>${esc(r.peso||r.peso_total_kg)}</td><td>${esc(r.volumes||r.volume_total)}</td><td>${esc(r.inicio)}</td><td>${esc(r.fim)}</td><td>${badge(r.status||'PENDENTE',resultClass(r.status||r.resultado))}</td><td><button class="btn secondary" onclick="details('${esc(r.lote||'')}')">Ver</button></td></tr>`).join(''));}
function carregamentosPage(){const d=userCars();return tablePage('Meus Carregamentos','Apenas carregamentos vinculados ao seu usuário.',['Romaneio','Rota/Destino','Motorista','Placa','Peso','Volumes','Início','Fim','Resultado'],d.map(r=>`<tr><td>${esc(r.romaneio||r.numero_romaneio)}</td><td>${esc(r.destino||r.rota)}</td><td>${esc(r.motorista)}</td><td>${esc(r.placa||r.veiculo)}</td><td>${esc(r.peso||r.peso_total_kg)}</td><td>${esc(r.volumes||r.volume_total)}</td><td>${esc(r.inicio)}</td><td>${esc(r.fim)}</td><td>${badge(r.resultado||r.status||'PENDENTE',resultClass(r.resultado||r.status))}</td></tr>`).join(''));}
function conferenciasPage(){const d=userConfs();return tablePage('Minhas Conferências','Somente usuários com permissão de conferência.',['Operação','Lote/Pedido','Data/Hora','Resultado','Divergência','Qtd. divergente','Observação'],d.map(r=>`<tr><td>${esc(r.operacao||r.tipo_operacao)}</td><td>${esc(r.referencia||r.lote||r.pedido)}</td><td>${esc(r.hora||r.fim||r.inicio)}</td><td>${badge(r.resultado||'PENDENTE',resultClass(r.resultado))}</td><td>${esc(r.ocorrencia||'—')}</td><td>${esc(r.quantidade_divergente||r.qtd||'—')}</td><td>${esc(r.observacao||'—')}</td></tr>`).join(''));}
function atividadesPage(){const d=userActs();return tablePage('Minhas Atividades','Preserva a descrição original registrada no SIGA, mesmo quando o texto varia.',['Hora','Tipo','Descrição original','Status','Detalhes'],d.map(e=>`<tr><td>${esc(e.hora||e.inicio||'')}</td><td>${esc(e.tipo||'Atividade')}</td><td>${esc(e.descricao_original||e.descricao||e.atividade||e.texto||e.detalhes||'')}</td><td>${badge(e.status||'PENDENTE',resultClass(e.status))}</td><td><button class="btn secondary" onclick="showToast('Detalhes da atividade')">Ver</button></td></tr>`).join(''));}
function desempenhoPage(){const t=totals();const max=Math.max(t.s,t.c,t.f,t.a,1);return `<div class="page-title"><h1>Meu Desempenho</h1><p>Resumo calculado a partir das operações vinculadas ao usuário.</p></div><div class="cards"><div class="stat blue"><div class="stat-top">SEPARAÇÕES</div><strong>${t.s}</strong><small>Registros</small></div><div class="stat green"><div class="stat-top">CARREGAMENTOS</div><strong>${t.c}</strong><small>Registros</small></div><div class="stat purple"><div class="stat-top">CONFERÊNCIAS</div><strong>${t.f}</strong><small>Registros</small></div><div class="stat dark"><div class="stat-top">ATIVIDADES</div><strong>${t.a}</strong><small>Registros</small></div></div><div class="grid2"><div class="panel"><h3>Desempenho</h3><div class="sub">Indicadores em barras horizontais</div>${bar('Separações',t.s,max,'')}${bar('Carregamentos',t.c,max,'green')}${bar('Conferências',t.f,max,'purple')}${bar('Atividades',t.a,max,'dark')}</div><div class="panel"><h3>Resultados</h3><div class="sub">Conferências e carregamentos</div>${bar('Conferências OK',t.fok,Math.max(t.f,1),'green')}${bar('Conferências NÃO OK',t.fbad,Math.max(t.f,1),'red')}${bar('Carregamentos OK',t.cok,Math.max(t.c,1),'green')}${bar('Carregamentos NÃO OK',t.cbad,Math.max(t.c,1),'red')}</div></div>`;}
function perfilPage(){return `<div class="page-title"><h1>Perfil / Acesso</h1><p>Seu perfil e as permissões liberadas pelo administrador.</p></div><div class="profile"><div class="panel profile-card"><div class="avatar">${esc(state.user.avatar||'US')}</div><h3>${esc(state.user.name)}</h3><p class="sub">${esc(state.user.role||'Operador')}</p><div class="info" style="margin-top:15px;text-align:left"><small>Unidade</small><b>${esc(state.user.cd||'CDD')}</b></div></div><div class="panel"><h3>Permissões</h3>${permission('separacoes','Visualizar minhas separações')}${permission('carregamentos','Visualizar meus carregamentos')}${permission('atividades','Visualizar minhas atividades')}${permission('desempenho','Visualizar meu desempenho')}${permission('conferencias','Visualizar minhas conferências')}<button class="btn" style="margin-top:12px" onclick="showToast('Permissões administradas pelo perfil Autor')">Solicitar alteração</button></div></div>`;}
function permission(k,label){return `<div class="permission"><input type="checkbox" ${state.permissions[k]?'checked':''} disabled> ${esc(label)}</div>`;}
function adminPage(){return `<div class="page-title"><h1>Gestão de Usuários e Permissões</h1><p>Perfil Autor / Administrador • crie usuários, senhas e libere funções individualmente.</p></div><div class="admin-grid"><div class="panel"><div class="panel-title"><div><h3>👤 Usuários cadastrados</h3><div class="sub">Acesso controlado por usuário</div></div><button class="btn" onclick="showToast('Formulário de novo usuário')">+ Criar usuário</button></div><div class="user-list" style="margin-top:12px">${users.map(u=>`<div class="user-row"><div class="avatar">${u[0]}</div><div><b>${esc(u[1])}</b><small>${esc(u[2])} • ${esc(u[3])}</small></div><button class="btn secondary" onclick="showToast('Editando ${esc(u[1])}')">Editar</button></div>`).join('')}</div></div><div class="panel"><h3>🔐 Novo acesso</h3><div class="filters" style="margin-top:12px"><input placeholder="Nome completo"><input placeholder="Usuário"><input placeholder="Criar senha"><select><option>Operador</option><option>Conferente</option><option>Operador + Conferente</option><option>Administrador</option></select></div><h3 style="margin-top:8px">Liberar funções</h3><div class="checkgrid"><label class="check"><input type="checkbox" checked> Minhas Separações</label><label class="check"><input type="checkbox"> Meus Carregamentos</label><label class="check"><input type="checkbox" checked> Minhas Atividades</label><label class="check"><input type="checkbox"> Meu Desempenho</label><label class="check"><input type="checkbox"> Minhas Conferências</label></div><button class="btn" style="margin-top:13px" onclick="showToast('Usuário criado com permissões selecionadas')">Criar acesso</button></div></div>`;}
function details(lote){const r=userSeps().find(x=>(x.lote||x.numero_lote)===lote)||userSeps()[0];if(!r){state.page='separacoes';render();return;}document.querySelector('#main').innerHTML=`<div class="page-title"><button class="btn secondary" onclick="render()">← Voltar</button><h1 style="margin-top:8px">Detalhes da separação</h1><p>Operação ${esc(lote)}</p></div><div class="panel"><div class="hero"><div><h1 style="font-size:16px">Lote ${esc(r.lote||'')}</h1><p>Pedido ${esc(r.pedido||'')} • Destino ${esc(r.destino||'')}</p></div>${badge(r.status||'PENDENTE',resultClass(r.status||r.resultado))}</div><div class="detail-grid"><div class="info"><small>Peso</small><b>${esc(r.peso||'')}</b></div><div class="info"><small>Volumes</small><b>${esc(r.volumes||'')}</b></div><div class="info"><small>Início</small><b>${esc(r.inicio||'')}</b></div><div class="info"><small>Fim</small><b>${esc(r.fim||'')}</b></div></div></div>`;}
function filterRows(v){const q=norm(v);document.querySelectorAll('#dataRows tr').forEach(r=>r.style.display=norm(r.innerText).includes(q)?'':'none');}
function applyFilters(){const q=document.querySelector('.filters input')?.value||'';filterRows(q);showToast('Filtro aplicado');}
function showToast(m){const t=document.querySelector('#toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}}
function closeMenu(){document.querySelector('#sidebar')?.classList.remove('open');document.querySelector('#overlay')?.classList.remove('show');document.querySelector('aside')?.classList.remove('open');}
function login(){const u=(document.querySelector('#u')?.value||'').trim();const p=document.querySelector('#pw')?.value||'';const msg=document.querySelector('#loginmsg');if(!u||!p){if(msg)msg.textContent='Informe usuário e senha.';return;}state.user={id:u.toLowerCase(),usuario:u,username:u,name:u==='01022005'?'Marco':u,role:u==='01022005'?'Autor / Administrador':'Operador',cd:document.querySelector('#fil')?.value||'CDD',avatar:(u==='01022005'?'MA':u.slice(0,2).toUpperCase())};state.permissions={separacoes:true,carregamentos:true,atividades:true,desempenho:true,conferencias:u==='01022005',admin:u==='01022005'};localStorage.setItem(STORAGE_USER,JSON.stringify(state.user));localStorage.setItem('siga30_portal_permissions_v2',JSON.stringify(state.permissions));state.page='home';render();refreshData(true);}
function logout(){localStorage.removeItem(STORAGE_USER);localStorage.removeItem('siga30_portal_permissions_v2');state.user=null;document.querySelector('#app')?.classList.add('hide');document.querySelector('#login')?.classList.remove('hide');}
function restoreSession(){try{const u=JSON.parse(localStorage.getItem(STORAGE_USER)||'null');if(!u)return false;state.user=u;const p=JSON.parse(localStorage.getItem('siga30_portal_permissions_v2')||'null');if(p)state.permissions={...state.permissions,...p};render();return true;}catch{return false;}}
async function refreshData(manual=false){if(!state.user||state.syncing)return;state.syncing=true;try{portalData=loadData();const url=(localStorage.getItem(STORAGE_API)||'').trim();if(url){const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const json=await res.json();portalData={separacoes:Array.isArray(json.separacoes)?json.separacoes:portalData.separacoes,carregamentos:Array.isArray(json.carregamentos)?json.carregamentos:portalData.carregamentos,atividades:Array.isArray(json.atividades)?json.atividades:portalData.atividades,conferencias:Array.isArray(json.conferencias)?json.conferencias:portalData.conferencias};saveData();}state.lastSync=Date.now();if(manual)showToast('Informações atualizadas');if(state.user)render();}catch(e){state.lastSync=Date.now();if(manual)showToast('Dados locais atualizados; API não disponível.');}finally{state.syncing=false;}}
function clock(){const e=document.querySelector('#clock');if(e)e.textContent=new Date().toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});}
document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#menuBtn')?.addEventListener('click',()=>{document.querySelector('#sidebar')?.classList.add('open');document.querySelector('#overlay')?.classList.add('show');});document.querySelector('#overlay')?.addEventListener('click',closeMenu);document.querySelector('#profileBtn')?.addEventListener('click',()=>{state.page='perfil';render();});setInterval(clock,1000);clock();if(!restoreSession()){document.querySelector('#login')?.classList.remove('hide');document.querySelector('#app')?.classList.add('hide');}setInterval(()=>refreshData(false),10000);});
