const KEY='siga30_portal_users_v2';
const defaultUsers=[
 {id:'u-admin',nome:'Marco',usuario:'marco',senha:'01022005',filial:'CDD',funcao:'Autor / Administrador',admin:true,ativo:true,permissoes:{separacoes:true,carregamentos:true,atividades:true,conferencias:true,desempenho:true}},
 {id:'u-joao',nome:'João Silva',usuario:'joao',senha:'1234',filial:'CDD',funcao:'Operador',admin:false,ativo:true,permissoes:{separacoes:true,carregamentos:true,atividades:true,conferencias:false,desempenho:true}},
 {id:'u-ana',nome:'Ana Souza',usuario:'ana',senha:'1234',filial:'CDD',funcao:'Conferente',admin:false,ativo:true,permissoes:{separacoes:true,carregamentos:false,atividades:true,conferencias:true,desempenho:true}},
 {id:'u-carlos',nome:'Carlos Lima',usuario:'carlos',senha:'1234',filial:'CDD',funcao:'Operador + Conferente',admin:false,ativo:true,permissoes:{separacoes:true,carregamentos:true,atividades:true,conferencias:true,desempenho:true}}
];
let users=loadUsers(), currentUser=null, page='home';
const icons={
 home:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5M9 20v-5.5h6V20"/></svg>`,
 separacoes:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h10"/><circle cx="18" cy="18" r="2.5"/></svg>`,
 carregamentos:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 7h11v10H3zM14 10h4l3 3v4h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></svg>`,
 conferencias:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/><circle cx="12" cy="12" r="9"/></svg>`,
 atividades:`<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>`,
 desempenho:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19V10M12 19V5M19 19v-8"/><path d="M3 19h18"/></svg>`,
 usuarios:`<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3"/><path d="M3.5 19c.7-3.1 2.5-4.7 5.5-4.7s4.8 1.6 5.5 4.7"/><path d="M16 11h5M18.5 8.5v5"/></svg>`,
 perfil:`<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3"/><path d="M5 20c.8-3.5 3.1-5.2 7-5.2s6.2 1.7 7 5.2"/></svg>`,
 sair:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10 5H5v14h5M14 8l4 4-4 4M9 12h9"/></svg>`
};
const navs=[['home','home','Início','always'],['separacoes','separacoes','Minhas Separações','separacoes'],['carregamentos','carregamentos','Meus Carregamentos','carregamentos'],['conferencias','conferencias','Minhas Conferências','conferencias'],['atividades','atividades','Minhas Atividades','atividades'],['desempenho','desempenho','Meu Desempenho','desempenho'],['usuarios','usuarios','Cadastrar Usuários','admin'],['perfil','perfil','Meu Perfil','always'],['sair','sair','Sair','always']];
const SYNC_KEY='siga30_portal_sync_v1';
const sampleActivities=[
 {id:'a1',hora:'08:15',tipo:'Atividade',descricao_original:'Abastecimento de endereço A-12',status:'Finalizada',resultado:'OK',usuario_id:'u-joao'},
 {id:'a2',hora:'09:02',tipo:'Atividade',descricao_original:'Organização de estoque — corredor 04',status:'Finalizada',resultado:'OK',usuario_id:'u-joao'},
 {id:'a3',hora:'10:20',tipo:'Atividade',descricao_original:'Movimentação interna — área CDD',status:'Finalizada',resultado:'OK',usuario_id:'u-joao'},
 {id:'a4',hora:'11:05',tipo:'Atividade',descricao_original:'Apoio operacional — doca 03',status:'Finalizada',resultado:'OK',usuario_id:'u-joao'},
 {id:'a5',hora:'12:15',tipo:'Atividade',descricao_original:'Inventário — endereço B-07',status:'Em andamento',resultado:'PENDENTE',usuario_id:'u-joao'},
 {id:'a6',hora:'13:30',tipo:'Atividade',descricao_original:'Reposição — área de separação',status:'Finalizada',resultado:'OK',usuario_id:'u-joao'}
];
const sampleSeps=[
 {id:'s1',lote:'LT-1025',pedido:'PED-4587',destino:'Ponte Nova',peso:'860 kg',volumes:'42',inicio:'08:15',fim:'09:02',status:'Finalizada',resultado:'OK',usuario_id:'u-joao',operador:'João Silva'},
 {id:'s2',lote:'LT-1038',pedido:'PED-4621',destino:'Viçosa',peso:'620 kg',volumes:'31',inicio:'10:20',fim:'11:10',status:'Em andamento',resultado:'PENDENTE',usuario_id:'u-joao',operador:'João Silva'},
 {id:'s3',lote:'LT-1029',pedido:'PED-4601',destino:'Ubá',peso:'740 kg',volumes:'38',inicio:'11:45',fim:'12:30',status:'Finalizada',resultado:'OK',usuario_id:'u-joao',operador:'João Silva'}
];
const sampleCars=[
 {romaneio:'ROM-783',destino:'Ponte Nova',motorista:'João Silva',placa:'OFA-4452',peso:'12.500 kg',volumes:'48',inicio:'10:20',fim:'12:05',resultado:'OK',usuario_id:'u-joao'},
 {romaneio:'ROM-781',destino:'Rio Casca',motorista:'Pedro Alves',placa:'HKG-7810',peso:'7.400 kg',volumes:'28',inicio:'09:10',fim:'11:00',resultado:'NÃO OK',usuario_id:'u-joao'}
];
let portalData=loadPortalData();
function loadPortalData(){try{const x=JSON.parse(localStorage.getItem('siga30_portal_data_v1'));return x&&typeof x==='object'?{separacoes:x.separacoes||sampleSeps,atividades:x.atividades||sampleActivities,carregamentos:x.carregamentos||sampleCars}: {separacoes:sampleSeps,atividades:sampleActivities,carregamentos:sampleCars}}catch(e){return {separacoes:sampleSeps,atividades:sampleActivities,carregamentos:sampleCars}}}
function savePortalData(){localStorage.setItem('siga30_portal_data_v1',JSON.stringify(portalData))}
function getSyncConfig(){try{return JSON.parse(localStorage.getItem(SYNC_KEY))||{url:'',auto:true}}catch(e){return {url:'',auto:true}}}
function setSyncConfig(v){localStorage.setItem(SYNC_KEY,JSON.stringify(v))}
function pick(o,keys,def=''){for(const k of keys){if(o&&o[k]!==undefined&&o[k]!==null&&o[k]!=='')return o[k]}return def}
function normResult(v){const x=String(v??'').trim().toUpperCase();if(['OK','APROVADO','CONFORME','FINALIZADA','FINALIZADO'].includes(x))return 'OK';if(['NÃO OK','NAO OK','NOK','REPROVADO','DIVERGENTE','ERRO'].includes(x))return 'NÃO OK';return x||'PENDENTE'}
function normSeparation(o,i=0){return {id:String(pick(o,['id','separacao_id','operacao_id'],`sep-${i}`)),lote:String(pick(o,['lote','lote_numero','numero_lote','lote_id'])),pedido:String(pick(o,['pedido','numero_pedido','pedido_separacao','separacao','ordem'])) ,destino:String(pick(o,['destino','unidade_destino','rota','rota_destino'])),peso:String(pick(o,['peso','peso_total','peso_total_kg'])),volumes:String(pick(o,['volumes','volume','volume_total'])),inicio:String(pick(o,['inicio','inicio_separacao','data_inicio','started_at'])),fim:String(pick(o,['fim','fim_separacao','data_fim','finished_at'])),status:String(pick(o,['status','situacao'], '')),resultado:normResult(pick(o,['resultado','resultado_conferencia','conferencia_resultado'],'')),usuario_id:String(pick(o,['usuario_id','operador_id','user_id','responsavel_id','colaborador_id'],'')),operador:String(pick(o,['operador','operador_nome','responsavel_nome','usuario_nome'],'')),local_estoque:String(pick(o,['local_estoque','localEstoque','endereco_estoque'],'')),tipo_operacao:String(pick(o,['tipo_operacao','tipo','operacao_tipo'],'')),ocorrencia:String(pick(o,['ocorrencia','observacao','observações'],''))}}
function normActivity(o,i=0){const original=String(pick(o,['descricao_original','descricao','atividade','nome_atividade','texto','detalhes','observacao','observação','acao','ação'],''));return {id:String(pick(o,['id','atividade_id','evento_id'],`ati-${i}`)),hora:String(pick(o,['hora','data_hora','timestamp','inicio','created_at'],'')),tipo:String(pick(o,['tipo','tipo_atividade','categoria','evento_tipo'],'Atividade')),descricao_original:original,status:String(pick(o,['status','situacao'],'Finalizada')),resultado:normResult(pick(o,['resultado','resultado_conferencia','resultado_carregamento'],'')),usuario_id:String(pick(o,['usuario_id','operador_id','user_id','responsavel_id','colaborador_id'],'')),usuario_nome:String(pick(o,['usuario_nome','operador','responsavel_nome','nome_usuario'],'')),meta:o};}
function userMatches(o,u){const ids=[o.usuario_id,o.operador_id,o.user_id,o.responsavel_id,o.colaborador_id].filter(Boolean).map(String);const names=[o.operador,o.operador_nome,o.usuario_nome,o.responsavel_nome].filter(Boolean).map(x=>String(x).toLowerCase());return !ids.length&&!names.length || ids.includes(String(u.id)) || ids.includes(String(u.usuario)) || names.includes(String(u.nome).toLowerCase())}
async function syncFromSiga(){const cfg=getSyncConfig();if(!cfg.url){toast('Informe a URL da API do SIGA para sincronizar.','bad');return false}try{const r=await fetch(cfg.url,{headers:{'Accept':'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const raw=await r.json();const payload=raw.data||raw.result||raw;const sep=Array.isArray(payload.separacoes)?payload.separacoes:Array.isArray(payload.separations)?payload.separations:[];const ati=Array.isArray(payload.atividades)?payload.atividades:Array.isArray(payload.activities)?payload.activities:[];const car=Array.isArray(payload.carregamentos)?payload.carregamentos:Array.isArray(payload.loads)?payload.loads:[];if(sep.length)portalData.separacoes=sep.map(normSeparation);if(ati.length)portalData.atividades=ati.map(normActivity);if(car.length)portalData.carregamentos=car.map((o,i)=>({...sampleCars[0],...o,id:String(pick(o,['id','carregamento_id'],`car-${i}`)),usuario_id:String(pick(o,['usuario_id','operador_id','user_id','responsavel_id'],''))}));savePortalData();toast(`SIGA sincronizado: ${sep.length} separações e ${ati.length} atividades.`,'ok');render();return true}catch(e){toast(`Não foi possível sincronizar: ${e.message}`,'bad');return false}}
function importSigaJson(file){const rd=new FileReader();rd.onload=()=>{try{const raw=JSON.parse(rd.result),p=raw.data||raw.result||raw;const sep=Array.isArray(p.separacoes)?p.separacoes:[],ati=Array.isArray(p.atividades)?p.atividades:[],car=Array.isArray(p.carregamentos)?p.carregamentos:[];if(!sep.length&&!ati.length&&!car.length)throw new Error('JSON sem separacoes, atividades ou carregamentos');if(sep.length)portalData.separacoes=sep.map(normSeparation);if(ati.length)portalData.atividades=ati.map(normActivity);if(car.length)portalData.carregamentos=car;savePortalData();toast(`Dados importados: ${sep.length} separações e ${ati.length} atividades.`,'ok');render()}catch(e){toast(`JSON inválido: ${e.message}`,'bad')}};rd.readAsText(file)}
function syncPanel(){const c=getSyncConfig();return `<div class="panel" style="margin-top:12px"><h3>🔗 Integração com o SIGA 3.0</h3><div class="sub">O portal aceita os registros do SIGA original e preserva a descrição original das atividades.</div><div class="user-form" style="margin-top:12px"><div class="field" style="grid-column:1/-1"><label>URL da API/endpoint do SIGA</label><input id="syncUrl" value="${esc(c.url)}" placeholder="https://seu-siga/api/portal/sync"></div></div><div class="form-actions"><button class="btn" onclick="saveSyncAndRun()">Salvar e sincronizar</button><label class="btn secondary" style="cursor:pointer">Importar JSON do SIGA<input type="file" accept="application/json,.json" hidden onchange="importSigaJson(this.files[0])"></label></div><div class="sub" style="margin-top:10px">Formato aceito: <b>{ separacoes: [...], atividades: [...], carregamentos: [...] }</b>. O campo de atividade pode variar; o portal procura descricao_original, descricao, atividade, texto, detalhes, observacao etc.</div></div>`}
async function saveSyncAndRun(){setSyncConfig({url:document.querySelector('#syncUrl').value.trim(),auto:true});await syncFromSiga()}

const b=(t,c)=>`<span class="badge ${c}">${t}</span>`;
const bars=a=>a.map(x=>`<div class="barrow"><label>${x[0]}</label><div class="bar"><div class="fill ${x[3]||''}" style="width:${Math.min(100,Math.round(x[1]/x[2]*100))}%"></div></div><strong>${x[1]}</strong></div>`).join('');
function loadUsers(){try{const saved=JSON.parse(localStorage.getItem(KEY));return Array.isArray(saved)&&saved.length?saved:structuredClone(defaultUsers)}catch(e){return structuredClone(defaultUsers)}}
function saveUsers(){localStorage.setItem(KEY,JSON.stringify(users))}
function initials(n){return n.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function renderNav(){if(!currentUser)return;document.querySelector('#nav').innerHTML=navs.filter(x=>x[3]==='always'||x[3]==='admin'&&currentUser.admin||currentUser.permissoes[x[3]]).map(x=>`<button class="${page===x[0]?'active':''}" onclick="go('${x[0]}')"><span class="nav-icon">${icons[x[1]]}</span><span class="nav-text">${x[2]}</span></button>`).join('')}
function updateIdentity(){const n=currentUser.nome, ini=initials(n);document.querySelector('#sideName').textContent=n;document.querySelector('#sideRole').textContent=currentUser.funcao;document.querySelector('#sideInitials').textContent=ini;document.querySelector('#headerWho').textContent=`${currentUser.filial} · ${n}`;document.querySelector('#headerInitials').textContent=ini}
function allowed(p){if(p==='usuarios')return !!currentUser?.admin;if(['home','perfil','sair'].includes(p))return true;return !!currentUser?.permissoes[p]}
function go(p){if(p==='sair'){logout();return}if(!allowed(p)){toast('Você não tem permissão para acessar esta tela.','bad');return}page=p;render();document.querySelector('aside').classList.remove('open')}
function render(){if(!currentUser)return;renderNav();updateIdentity();const f={home,separacoes,carregamentos,conferencias,atividades,desempenho,usuarios,perfil};document.querySelector('#main').innerHTML=(f[page]||home)()}
function home(){return `<div class="title"><h1>Olá, ${esc(currentUser.nome)}!</h1><p>Aqui está o resumo das suas atividades de hoje.</p></div><div class="cards"><div class="card c1"><small>SEPARAÇÕES</small><strong>12</strong><small>Hoje</small></div><div class="card c2"><small>CARREGAMENTOS</small><strong>8</strong><small>Hoje</small></div><div class="card c3"><small>CONFERÊNCIAS</small><strong>7</strong><small>Hoje</small></div><div class="card c4"><small>ATIVIDADES</small><strong>6</strong><small>Hoje</small></div></div><div class="two"><div class="panel"><h3>📋 Atividades feitas hoje</h3><div class="sub">Informações recebidas do SIGA original, preservando a descrição da atividade.</div>${portalData.atividades.filter(e=>userMatches(e,currentUser)).map(e=>`<div class="event"><i class="dot"></i><div><b>${e[0]} • ${e[1]}</b><small>${esc(e[2])}</small></div>${b(e[3],e[4])}</div>`).join('')}</div><div><div class="panel"><h3>📊 Atividades de hoje</h3><div class="sub">Gráfico horizontal</div>${bars([['Separações',12,12],['Carregamentos',8,12,'green'],['Conferências',7,12,'purple'],['Atividades',6,8,'dark']])}</div><div class="panel" style="margin-top:12px"><h3>📈 Resultados das operações</h3><div class="sub">OK / NÃO OK</div>${bars([['Conferências OK',5,7,'green'],['Conferências NÃO OK',2,7,'red'],['Carregamentos OK',6,8,'green'],['Carregamentos NÃO OK',2,8,'red']])}</div></div></div>`}
function table(title,sub,h,rows){return `<div class="title"><h1>${title}</h1><p>${sub}</p></div><div class="panel"><div class="filters"><input placeholder="Pesquisar..." oninput="filter(this.value)"><select><option>Hoje</option><option>Últimos 7 dias</option><option>Este mês</option></select><button class="btn">Filtrar</button></div><div class="tablewrap"><table class="table"><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody id="rows">${rows}</tbody></table></div></div>`}
function separacoes(){return table('Minhas Separações','Somente operações vinculadas ao usuário conectado.',['Lote','Pedido','Destino','Peso','Volumes','Início','Fim','Status'],seps.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>${r[5]}</td><td>${r[6]}</td><td>${b(r[7],r[8])}</td></tr>`).join(''))}
function carregamentos(){return table('Meus Carregamentos','Somente operações vinculadas ao usuário conectado.',['Romaneio','Destino','Motorista','Placa','Peso','Volumes','Início','Fim','Resultado'],cars.map(r=>`<tr>${r.map((x,i)=>`<td>${i===8?b(x,r[9]):x}</td>`).join('')}</tr>`).join(''))}
function conferencias(){return table('Minhas Conferências','Registro liberado somente quando a permissão de conferência estiver ativa.',['Operação','Lote/Pedido','Hora','Resultado','Divergência','Qtd.','Observação'],conf.map(r=>`<tr>${r.map((x,i)=>`<td>${i===3?b(x,x==='OK'?'ok':'bad'):x}</td>`).join('')}</tr>`).join(''))}
function atividades(){return table('Minhas Atividades','O texto abaixo pode variar a cada lançamento. O portal preserva a descrição original recebida do SIGA.',['Hora','Tipo','Descrição original do SIGA','Status'],activities.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${esc(r[2])}</td><td>${b(r[3],r[4])}</td></tr>`).join(''))}
function desempenho(){return `<div class="title"><h1>Meu Desempenho</h1><p>Indicadores separados por tipo de operação.</p></div><div class="cards"><div class="card c1"><small>SEPARAÇÕES</small><strong>12</strong></div><div class="card c2"><small>CARREGAMENTOS</small><strong>8</strong></div><div class="card c3"><small>CONFERÊNCIAS</small><strong>7</strong></div><div class="card c4"><small>ATIVIDADES</small><strong>6</strong></div></div><div class="panel" style="margin-top:12px"><h3>Desempenho</h3>${bars([['Separações',12,15],['Carregamentos',8,10,'green'],['Conferências',7,10,'purple'],['Atividades',6,8,'dark']])}</div>`}
function usuarios(){if(!currentUser?.admin)return denied();return `<div class="title"><h1>Cadastrar Usuários</h1><p>Somente o Autor / Administrador pode criar usuários e liberar funções individualmente.</p></div><div class="panel"><h3>Novo usuário</h3><div class="sub">Acesso, função e permissões ficam vinculados ao usuário.</div><div class="user-form" style="margin-top:14px"><div class="field"><label>Nome completo</label><input id="newNome" placeholder="Ex.: João da Silva"></div><div class="field"><label>Usuário de acesso</label><input id="newUsuario" placeholder="Ex.: joao.silva"></div><div class="field"><label>Senha</label><input id="newSenha" type="password" placeholder="Crie uma senha"></div><div class="field"><label>Filial</label><select id="newFilial"><option>CDD</option></select></div><div class="field"><label>Função</label><select id="newFuncao"><option>Operador</option><option>Conferente</option><option>Operador + Conferente</option></select></div><div class="field"><label>Status</label><select id="newAtivo"><option value="true">Ativo</option><option value="false">Bloqueado</option></select></div></div><h3 style="margin-top:18px">Permissões individuais</h3><div class="checks"><label><input id="pSep" type="checkbox" checked> Visualizar minhas separações</label><label><input id="pCar" type="checkbox" checked> Visualizar meus carregamentos</label><label><input id="pAti" type="checkbox" checked> Visualizar minhas atividades</label><label><input id="pCon" type="checkbox"> Visualizar minhas conferências</label><label><input id="pDes" type="checkbox" checked> Visualizar meu desempenho</label></div><div class="form-actions"><button class="btn" onclick="createUser()">Cadastrar usuário</button><button class="btn secondary" onclick="clearUserForm()">Limpar</button></div></div><div class="panel" style="margin-top:12px"><h3>Usuários cadastrados</h3><div class="tablewrap"><table class="table"><thead><tr><th>Nome</th><th>Usuário</th><th>Função</th><th>Filial</th><th>Permissões</th><th>Status</th><th>Ação</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.nome)}</td><td>${esc(u.usuario)}</td><td>${esc(u.funcao)}</td><td>${esc(u.filial)}</td><td>${permSummary(u)}</td><td>${b(u.ativo?'ATIVO':'BLOQUEADO',u.ativo?'ok':'bad')}</td><td>${u.admin?'<span class="sub">Administrador</span>':`<button class="btn ${u.ativo?'danger':'secondary'}" onclick="toggleUser('${u.id}')">${u.ativo?'Bloquear':'Ativar'}</button>`}</td></tr>`).join('')}</tbody></table></div></div>${syncPanel()}`}
function permSummary(u){const p=u.permissoes||{};return ['separacoes','carregamentos','atividades','conferencias','desempenho'].filter(k=>p[k]).length+'/5 liberadas'}
function createUser(){if(!currentUser?.admin)return denied();const nome=document.querySelector('#newNome').value.trim(),usuario=document.querySelector('#newUsuario').value.trim().toLowerCase(),senha=document.querySelector('#newSenha').value,filial=document.querySelector('#newFilial').value,funcao=document.querySelector('#newFuncao').value,ativo=document.querySelector('#newAtivo').value==='true';if(!nome||!usuario||!senha){toast('Preencha nome, usuário e senha.','bad');return}if(!/^[a-z0-9._-]+$/.test(usuario)){toast('Usuário deve usar apenas letras, números, ponto, _ ou -.','bad');return}if(users.some(u=>u.usuario===usuario)){toast('Esse usuário já existe.','bad');return}const u={id:'u-'+Date.now(),nome,usuario,senha,filial,funcao,admin:false,ativo,permissoes:{separacoes:document.querySelector('#pSep').checked,carregamentos:document.querySelector('#pCar').checked,atividades:document.querySelector('#pAti').checked,conferencias:document.querySelector('#pCon').checked,desempenho:document.querySelector('#pDes').checked}};users.push(u);saveUsers();clearUserForm();render();toast('Usuário cadastrado com sucesso.','ok')}
function clearUserForm(){['newNome','newUsuario','newSenha'].forEach(id=>document.querySelector('#'+id).value='');document.querySelector('#pSep').checked=true;document.querySelector('#pCar').checked=true;document.querySelector('#pAti').checked=true;document.querySelector('#pCon').checked=false;document.querySelector('#pDes').checked=true}
function toggleUser(id){if(!currentUser?.admin)return denied();const u=users.find(x=>x.id===id);if(!u)return;u.ativo=!u.ativo;saveUsers();render();toast(`${u.nome}: ${u.ativo?'acesso ativado':'acesso bloqueado'}.`,'ok')}
function perfil(){return `<div class="title"><h1>Meu Perfil</h1><p>Dados do usuário conectado.</p></div><div class="profile"><div class="panel" style="text-align:center"><div class="me" style="justify-content:center"><i>${initials(currentUser.nome)}</i></div><h3>${esc(currentUser.nome)}</h3><div class="sub">${esc(currentUser.funcao)} • ${esc(currentUser.filial)}</div></div><div class="panel"><h3>Minhas permissões</h3>${[['separacoes','Visualizar minhas separações'],['carregamentos','Visualizar meus carregamentos'],['atividades','Visualizar minhas atividades'],['conferencias','Visualizar minhas conferências'],['desempenho','Visualizar meu desempenho']].map(x=>`<div class="permission">${currentUser.permissoes[x[0]]?'☑':'☐'} ${x[1]}</div>`).join('')}</div></div>`}
function denied(){return `<div class="panel"><h3>Acesso não autorizado</h3><p class="sub">Seu usuário não possui permissão para esta área.</p></div>`}
function filter(v){document.querySelectorAll('#rows tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(v.toLowerCase())?'':'none')}
function login(){const usuario=document.querySelector('#u').value.trim().toLowerCase(),senha=document.querySelector('#pw').value,filial=document.querySelector('#fil').value,msg=document.querySelector('#loginmsg');const u=users.find(x=>x.usuario===usuario&&x.senha===senha&&x.filial===filial);if(!u){msg.textContent='Usuário, senha ou filial inválidos.';return}if(!u.ativo){msg.textContent='Usuário bloqueado. Procure o administrador.';return}currentUser=u;page='home';msg.textContent='';document.querySelector('#login').classList.add('hide');document.querySelector('#app').classList.remove('hide');render();const cfg=getSyncConfig();if(cfg.auto&&cfg.url)syncFromSiga()}
function logout(){currentUser=null;page='home';document.querySelector('#app').classList.add('hide');document.querySelector('#login').classList.remove('hide');document.querySelector('#u').value='';document.querySelector('#pw').value='';document.querySelector('#loginmsg').textContent=''}
function toast(msg,type='ok'){let el=document.querySelector('.toast');if(!el){el=document.createElement('div');el.className='toast';document.body.appendChild(el)}el.className='toast '+type;el.textContent=msg;clearTimeout(window._toast);window._toast=setTimeout(()=>el.remove(),2600)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
